<?php

return [
    [
        'id' => 1,
        'cycle_id' => 'primaire',
        'name' => 'préscolaire',
        'level' => 1,
        'alias' => 'pre',
    ],
    [
        'id' => 2,
        'cycle_id' => 'primaire',
        'name' => '1re AP',
        'level' => 2,
        'alias' => '1ap',
    ],
    [
        'id' => 3,
        'cycle_id' => 'primaire',
        'name' => '2e AP',
        'level' => 3,
        'alias' => '2ap',
    ],
    [
        'id' => 4,
        'cycle_id' => 'primaire',
        'name' => '3e AP',
        'level' => 4,
        'alias' => '3ap',
    ],
    [
        'id' => 5,
        'cycle_id' => 'primaire',
        'name' => '4e AP',
        'level' => 5,
        'alias' => '4ap',
    ],
    [
        'id' => 6,
        'cycle_id' => 'primaire',
        'name' => '5e AP',
        'level' => 6,
        'alias' => '5ap',
    ],
    [
        'id' => 7,
        'cycle_id' => 'moyen',
        'name' => '1re AM',
        'level' => 7,
        'alias' => '1am',
    ],
    [
        'id' => 8,
        'cycle_id' => 'moyen',
        'name' => '2e AM',
        'level' => 8,
        'alias' => '2am',
    ],
    [
        'id' => 9,
        'cycle_id' => 'moyen',
        'name' => '3e AM',
        'level' => 9,
        'alias' => '3am',
    ],
    [
        'id' => 10,
        'cycle_id' => 'moyen',
        'name' => '4e AM',
        'level' => 10,
        'alias' => '4am',
    ],
    [
        'id' => 11,
        'cycle_id' => 'secondaire',
        'name' => '1re AS TC sciences et technologie',
        'level' => 11,
        'alias' => '1as-st',
    ],
    [
        'id' => 12,
        'cycle_id' => 'secondaire',
        'name' => '1re AS TC lettres',
        'level' => 11,
        'alias' => '1as-l',
    ],
    [
        'id' => 13,
        'cycle_id' => 'secondaire',
        'name' => '2e AS sciences expérimentales',
        'level' => 12,
        'alias' => '2as-s',
    ],
    [
        'id' => 14,
        'cycle_id' => 'secondaire',
        'name' => '2e AS gestion et economie',
        'level' => 12,
        'alias' => '2as-ge',
    ],
    [
        'id' => 15,
        'cycle_id' => 'secondaire',
        'name' => '2e AS math',
        'level' => 12,
        'alias' => '2as-m',
    ],
    [
        'id' => 16,
        'cycle_id' => 'secondaire',
        'name' => '2e AS technique mathematique',
        'level' => 12,
        'alias' => '2as-tm',
    ],
    [
        'id' => 17,
        'cycle_id' => 'secondaire',
        'name' => '2e AS langues étrangères',
        'level' => 12,
        'alias' => '2as-le',
    ],
    [
        'id' => 18,
        'cycle_id' => 'secondaire',
        'name' => '2e AS lettres - philosophie',
        'level' => 12,
        'alias' => '2as-lp',
    ],
    [
        'id' => 19,
        'cycle_id' => 'secondaire',
        'name' => '3e AS sciences expérimentales',
        'level' => 13,
        'alias' => '3as-s',
    ],
    [
        'id' => 20,
        'cycle_id' => 'secondaire',
        'name' => '3e AS gestion et economie',
        'level' => 13,
        'alias' => '3as-ge',
    ],
    [
        'id' => 21,
        'cycle_id' => 'secondaire',
        'name' => '3e AS math',
        'level' => 13,
        'alias' => '3as-m',
    ],
    [
        'id' => 22,
        'cycle_id' => 'secondaire',
        'name' => '3e AS technique mathematique',
        'level' => 13,
        'alias' => '3as-tm',
    ],
    [
        'id' => 23,
        'cycle_id' => 'secondaire',
        'name' => '3e AS langues étrangères',
        'level' => 13,
        'alias' => '3as-le',
    ],
    [
        'id' => 24,
        'cycle_id' => 'secondaire',
        'name' => '3e AS lettres - philosophie',
        'level' => 13,
        'alias' => '3as-lp',
    ],
];
